name: Generate and Deploy Pages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - uses: actions/configure-pages@v5
      - name: Smudge
        run: perl -i dev/git_commit_filter.pl smudge worker/service-worker.ts src/main.ts
      - name: Build pages
        run: npm run build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
      - uses: actions/deploy-pages@v4
